<?php

require_once '../system/controller/AutenticarClass.php';

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-06-16 at 14:21:53.
 */
class AutenticarClassTest extends PHPUnit_Framework_TestCase {

    /**
     * @var AutenticarClass
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new AutenticarClass;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * Generated from @assert (array('user_name'=>"rodrigo",'keyu'=>1)) > 0.
     *
     * @covers AutenticarClass::logar
     */
    public function testLogar() {
        $this->assertGreaterThan(
                0
                , $this->object->logar(array('user_name' => "rodrigo", 'keyu' => 1))
        );
    }

    /**
     * Generated from @assert (array('user_name'=>"rodrigo",'keyu'=>1)) <= 0.
     *
     * @covers AutenticarClass::logar
     */
    public function testLogar2() {
        $this->assertLessThanOrEqual(
                0
                , $this->object->logar(array('user_name' => "rodrigo", 'keyu' => 1))
        );
    }

    /**
     * Generated from @assert (array('user_name'=>"investidor2",'keyu'=>1)) > 0.
     *
     * @covers AutenticarClass::logar
     */
    public function testLogar3() {
        $this->assertGreaterThan(
                0
                , $this->object->logar(array('user_name' => "investidor2", 'keyu' => 1))
        );
    }

    /**
     * Generated from @assert (array('user_name'=>"investidor2",'keyu'=>1)) <= 0.
     *
     * @covers AutenticarClass::logar
     */
    public function testLogar4() {
        $this->assertLessThanOrEqual(
                0
                , $this->object->logar(array('user_name' => "investidor2", 'keyu' => 1))
        );
    }

    /**
     * Generated from @assert (array('user_name'=>"professor2",'keyu'=>1)) <= 0.
     *
     * @covers AutenticarClass::logar
     */
    public function testLogar5() {
        $this->assertLessThanOrEqual(
                0
                , $this->object->logar(array('user_name' => "professor2", 'keyu' => 1))
        );
    }

    /**
     * Generated from @assert (array('user_name'=>"professor2",'keyu'=>1)) > 0.
     *
     * @covers AutenticarClass::logar
     */
    public function testLogar6() {
        $this->assertGreaterThan(
                0
                , $this->object->logar(array('user_name' => "professor2", 'keyu' => 1))
        );
    }

    /**
     * Generated from @assert (array('user_name'=>"professor",'keyu'=>1)) <= 0.
     *
     * @covers AutenticarClass::logar
     */
    public function testLogar7() {
        $this->assertLessThanOrEqual(
                0
                , $this->object->logar(array('user_name' => "professor", 'keyu' => 1))
        );
    }

    /**
     * Generated from @assert (array('user_name'=>"professor",'keyu'=>1)) > 0.
     *
     * @covers AutenticarClass::logar
     */
    public function testLogar8() {
        $this->assertGreaterThan(
                0
                , $this->object->logar(array('user_name' => "professor", 'keyu' => 1))
        );
    }

    /**
     * @covers AutenticarClass::identificarUsuario
     * @todo   Implement testIdentificarUsuario().
     */
    public function testIdentificarUsuario() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
