<?php

require_once '../system/controller/AutenticarClass.php';

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-06-19 at 00:43:22.
 */
class AutenticarClassTest extends PHPUnit_Framework_TestCase {

    /**
     * @var AutenticarClass
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new AutenticarClass;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * Generated from @assert (array('user_name'=>"rodrigo",'keyu'=>1)) > 0.
     *
     * @covers AutenticarClass::logar
     */
    public function testLogar() {
        $this->assertGreaterThan(
                0
                , $this->object->logar(array('user_name' => "rodrigo", 'keyu' => 1))
        );
    }

    /**
     * Generated from @assert (array('user_name'=>"rodrigo",'keyu'=>1)) <= 0.
     *
     * @covers AutenticarClass::logar
     */
    public function testLogar2() {
        $this->assertLessThanOrEqual(
                0
                , $this->object->logar(array('user_name' => "rodrigo", 'keyu' => 1))
        );
    }

    /**
     * Generated from @assert (array('user_name'=>"investidor2",'keyu'=>1)) > 0.
     *
     * @covers AutenticarClass::logar
     */
    public function testLogar3() {
        $this->assertGreaterThan(
                0
                , $this->object->logar(array('user_name' => "investidor2", 'keyu' => 1))
        );
    }

    /**
     * Generated from @assert (array('user_name'=>"investidor2",'keyu'=>1)) <= 0.
     *
     * @covers AutenticarClass::logar
     */
    public function testLogar4() {
        $this->assertLessThanOrEqual(
                0
                , $this->object->logar(array('user_name' => "investidor2", 'keyu' => 1))
        );
    }

    /**
     * Generated from @assert (array('user_name'=>"professor2",'keyu'=>1)) <= 0.
     *
     * @covers AutenticarClass::logar
     */
    public function testLogar5() {
        $this->assertLessThanOrEqual(
                0
                , $this->object->logar(array('user_name' => "professor2", 'keyu' => 1))
        );
    }

    /**
     * Generated from @assert (array('user_name'=>"professor2",'keyu'=>1)) > 0.
     *
     * @covers AutenticarClass::logar
     */
    public function testLogar6() {
        $this->assertGreaterThan(
                0
                , $this->object->logar(array('user_name' => "professor2", 'keyu' => 1))
        );
    }

    /**
     * Generated from @assert (array('user_name'=>"professor",'keyu'=>1)) <= 0.
     *
     * @covers AutenticarClass::logar
     */
    public function testLogar7() {
        $this->assertLessThanOrEqual(
                0
                , $this->object->logar(array('user_name' => "professor", 'keyu' => 1))
        );
    }

    /**
     * Generated from @assert (array('user_name'=>"professor",'keyu'=>1)) > 0.
     *
     * @covers AutenticarClass::logar
     */
    public function testLogar8() {
        $this->assertGreaterThan(
                0
                , $this->object->logar(array('user_name' => "professor", 'keyu' => 1))
        );
    }

    /**
     * Generated from @assert (1) == array('user_name'=>"rodrigo",'area_user'=>1,'acesso_user'=>1).
     *
     * @covers AutenticarClass::identificarUsuario
     */
    public function testIdentificarUsuario() {
        $this->assertEquals(
                array('user_name' => "rodrigo", 'area_user' => 1, 'acesso_user' => 1)
                , $this->object->identificarUsuario(1)
        );
    }

    /**
     * Generated from @assert (2) == array('user_name'=>"professor",'area_user'=>2,'acesso_user'=>1).
     *
     * @covers AutenticarClass::identificarUsuario
     */
    public function testIdentificarUsuario2() {
        $this->assertEquals(
                array('user_name' => "professor", 'area_user' => 2, 'acesso_user' => 1)
                , $this->object->identificarUsuario(2)
        );
    }

    /**
     * Generated from @assert (3) == array('user_name'=>"investidor",'area_user'=>3,'acesso_user'=>3).
     *
     * @covers AutenticarClass::identificarUsuario
     */
    public function testIdentificarUsuario3() {
        $this->assertEquals(
                array('user_name' => "investidor", 'area_user' => 3, 'acesso_user' => 3)
                , $this->object->identificarUsuario(3)
        );
    }

    /**
     * Generated from @assert (4) == array('user_name'=>"aluno",'area_user'=>1,'acesso_user'=>3).
     *
     * @covers AutenticarClass::identificarUsuario
     */
    public function testIdentificarUsuario4() {
        $this->assertEquals(
                array('user_name' => "aluno", 'area_user' => 1, 'acesso_user' => 3)
                , $this->object->identificarUsuario(4)
        );
    }

    /**
     * Generated from @assert (5) == array('user_name'=>"nome",'area_user'=>1,'acesso_user'=>3).
     *
     * @covers AutenticarClass::identificarUsuario
     */
    public function testIdentificarUsuario5() {
        $this->assertEquals(
                array('user_name' => "nome", 'area_user' => 1, 'acesso_user' => 3)
                , $this->object->identificarUsuario(5)
        );
    }

    /**
     * Generated from @assert (6) == array('user_name'=>"Maria",'area_user'=>2,'acesso_user'=>3).
     *
     * @covers AutenticarClass::identificarUsuario
     */
    public function testIdentificarUsuario6() {
        $this->assertEquals(
                array('user_name' => "Maria", 'area_user' => 2, 'acesso_user' => 3)
                , $this->object->identificarUsuario(6)
        );
    }

    /**
     * Generated from @assert (7) == array('user_name'=>"Joao",'area_user'=>1,'acesso_user'=>3).
     *
     * @covers AutenticarClass::identificarUsuario
     */
    public function testIdentificarUsuario7() {
        $this->assertEquals(
                array('user_name' => "Joao", 'area_user' => 1, 'acesso_user' => 3)
                , $this->object->identificarUsuario(7)
        );
    }

    /**
     * Generated from @assert (1) == array('user_name'=>"professor2",'area_user'=>1,'acesso_user'=>3).
     *
     * @covers AutenticarClass::identificarUsuario
     */
    public function testIdentificarUsuario8() {
        $this->assertEquals(
                array('user_name' => "professor2", 'area_user' => 1, 'acesso_user' => 3)
                , $this->object->identificarUsuario(1)
        );
    }

    /**
     * Generated from @assert (1) == array('user_name'=>"professor2",'area_user'=>2,'acesso_user'=>3).
     *
     * @covers AutenticarClass::identificarUsuario
     */
    public function testIdentificarUsuario9() {
        $this->assertEquals(
                array('user_name' => "professor2", 'area_user' => 2, 'acesso_user' => 3)
                , $this->object->identificarUsuario(1)
        );
    }

    /**
     * Generated from @assert (1) == array('user_name'=>"professor2",'area_user'=>3,'acesso_user'=>3).
     *
     * @covers AutenticarClass::identificarUsuario
     */
    public function testIdentificarUsuario10() {
        $this->assertEquals(
                array('user_name' => "professor2", 'area_user' => 3, 'acesso_user' => 3)
                , $this->object->identificarUsuario(1)
        );
    }

    /**
     * Generated from @assert (1) == array('user_name'=>"rodrigo",'area_user'=>1,'acesso_user'=>1).
     *
     * @covers AutenticarClass::identificarUsuario
     */
    public function testIdentificarUsuario11() {
        $this->assertEquals(
                array('user_name' => "rodrigo", 'area_user' => 1, 'acesso_user' => 1)
                , $this->object->identificarUsuario(1)
        );
    }

}
