<?php
require_once '../system/controller/Utilitaria.php';
/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-06-16 at 13:49:09.
 */
class UtilitariaTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Utilitaria
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Utilitaria;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * Generated from @assert ("12/01/2015 11:00") == "2015-01-12 11:00".
     *
     * @covers Utilitaria::inverterDateTime
     */
    public function testInverterDateTime() {
        $this->assertEquals(
                "2015-01-12 11:00"
                , $this->object->inverterDateTime("12/01/2015 11:00")
        );
    }

    /**
     * Generated from @assert ("11/01/2015 11:00") == "2015-01-11 11:00".
     *
     * @covers Utilitaria::inverterDateTime
     */
    public function testInverterDateTime2() {
        $this->assertEquals(
                "2015-01-11 11:00"
                , $this->object->inverterDateTime("11/01/2015 11:00")
        );
    }

    /**
     * Generated from @assert ("14/10/2015 11:00") == "2015-10-14 11:00".
     *
     * @covers Utilitaria::inverterDateTime
     */
    public function testInverterDateTime3() {
        $this->assertEquals(
                "2015-10-14 11:00"
                , $this->object->inverterDateTime("14/10/2015 11:00")
        );
    }

    /**
     * Generated from @assert ("13/09/2015 13:00") == "2015-09-13 13:00".
     *
     * @covers Utilitaria::inverterDateTime
     */
    public function testInverterDateTime4() {
        $this->assertEquals(
                "2015-09-13 13:00"
                , $this->object->inverterDateTime("13/09/2015 13:00")
        );
    }

    /**
     * Generated from @assert ("17/07/2015 11:00") == "2015-07-17 11:00".
     *
     * @covers Utilitaria::inverterDateTime
     */
    public function testInverterDateTime5() {
        $this->assertEquals(
                "2015-07-17 11:00"
                , $this->object->inverterDateTime("17/07/2015 11:00")
        );
    }

    /**
     * Generated from @assert ("34/03/2015 11:00") == "2015-03-34 11:00".
     *
     * @covers Utilitaria::inverterDateTime
     */
    public function testInverterDateTime6() {
        $this->assertEquals(
                "2015-03-34 11:00"
                , $this->object->inverterDateTime("34/03/2015 11:00")
        );
    }

    /**
     * Generated from @assert ("12/05/2015 14:00") == "2015-05-12 11:00".
     *
     * @covers Utilitaria::inverterDateTime
     */
    public function testInverterDateTime7() {
        $this->assertEquals(
                "2015-05-12 11:00"
                , $this->object->inverterDateTime("12/05/2015 14:00")
        );
    }

    /**
     * Generated from @assert ("29/02/2015 15:00") == "2015-01-29 16:00".
     *
     * @covers Utilitaria::inverterDateTime
     */
    public function testInverterDateTime8() {
        $this->assertEquals(
                "2015-01-29 16:00"
                , $this->object->inverterDateTime("29/02/2015 15:00")
        );
    }

    /**
     * Generated from @assert ("12/01/2015") == "2015-01-12".
     *
     * @covers Utilitaria::inverterDate
     */
    public function testInverterDate() {
        $this->assertEquals(
                "2015-01-12"
                , $this->object->inverterDate("12/01/2015")
        );
    }

    /**
     * Generated from @assert ("11/01/2015") == "2015-01-11".
     *
     * @covers Utilitaria::inverterDate
     */
    public function testInverterDate2() {
        $this->assertEquals(
                "2015-01-11"
                , $this->object->inverterDate("11/01/2015")
        );
    }

    /**
     * Generated from @assert ("14/10/2015") == "2015-10-14".
     *
     * @covers Utilitaria::inverterDate
     */
    public function testInverterDate3() {
        $this->assertEquals(
                "2015-10-14"
                , $this->object->inverterDate("14/10/2015")
        );
    }

    /**
     * Generated from @assert ("13/09/2015") == "2015-09-13".
     *
     * @covers Utilitaria::inverterDate
     */
    public function testInverterDate4() {
        $this->assertEquals(
                "2015-09-13"
                , $this->object->inverterDate("13/09/2015")
        );
    }

    /**
     * Generated from @assert ("17/07/2015") == "2015-07-17".
     *
     * @covers Utilitaria::inverterDate
     */
    public function testInverterDate5() {
        $this->assertEquals(
                "2015-07-17"
                , $this->object->inverterDate("17/07/2015")
        );
    }

    /**
     * Generated from @assert ("34/03/2015") == "2015-03-34".
     *
     * @covers Utilitaria::inverterDate
     */
    public function testInverterDate6() {
        $this->assertEquals(
                "2015-03-34"
                , $this->object->inverterDate("34/03/2015")
        );
    }

    /**
     * Generated from @assert ("12/05/2015") == "2015-05-12".
     *
     * @covers Utilitaria::inverterDate
     */
    public function testInverterDate7() {
        $this->assertEquals(
                "2015-05-12"
                , $this->object->inverterDate("12/05/2015")
        );
    }

    /**
     * Generated from @assert ("29/02/2015") == "2015-01-29".
     *
     * @covers Utilitaria::inverterDate
     */
    public function testInverterDate8() {
        $this->assertEquals(
                "2015-01-29"
                , $this->object->inverterDate("29/02/2015")
        );
    }

}
